server:
    port: 8082
spring:
    application:
        name: api-boot-sample-message-pipe-client
    cloud:
        nacos:
            server-addr: 127.0.0.1:8848
            username: nacos
            password: nacos
        compatibility-verifier:
            enabled: false
